data:
  data_directory: "data/raw/"
  keyboard_pattern: "*_keyboard_performance.csv"
  mouse_pattern: "*_mouse_performance.csv"
  emotion_pattern: "*_emotion_performance.csv"
  processed_file: "data/processed/features_labels.csv"

model:
  model_file: "data/models/emotion_model.pkl"
  test_size: 0.2
  random_state: 42
  cv_folds: 5

features:
  time_window_minutes: 2
  selected_features: 15

training:
  models:
    - name: "Random Forest"
      params:
        n_estimators: [100, 200, 300]
        max_depth: [10, 20, null]
        min_samples_split: [2, 5, 10]
    - name: "Gradient Boosting"
      params:
        n_estimators: [100, 200]
        learning_rate: [0.05, 0.1, 0.15]
        max_depth: [3, 4, 5]